# Generated by Django 5.0.3 on 2024-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='id',
            field=models.TextField(default='a149d7083e9544f38c02f4eba3d016fa', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
