# Generated by Django 5.0.3 on 2024-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0002_alter_documentsmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='id',
            field=models.TextField(default='34cb31e52b274a8096c9dec7d0c1e93d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
