# Generated by Django 5.0.3 on 2024-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0004_alter_documentsmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='id',
            field=models.TextField(default='07ff67885fb44595b8cbebc5913a7a12', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
