# Generated by Django 5.0.3 on 2024-03-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0007_alter_documentsmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='id',
            field=models.TextField(default='e49a182479ff4ab0a3cbffb647e6253e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
