# Generated by Django 5.0.3 on 2024-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_newsmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='id',
            field=models.TextField(default='7a960640dc6543598681df0ad99e04ab', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
