# Generated by Django 5.0.3 on 2024-03-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_tips', '0003_alter_usefultipsmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefultipsmodel',
            name='id',
            field=models.TextField(default='619c7b3c62b74c9ba02279584d31cba2', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
