# Generated by Django 5.0.3 on 2024-03-21 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SHRMBAdmissionModel',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SHRMB Admission',
                'verbose_name_plural': 'SHRMB Admissions',
            },
        ),
        migrations.CreateModel(
            name='SHRMBDepartmentModel',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
            options={
                'verbose_name': 'SHRMB Department',
                'verbose_name_plural': 'SHRMB Departments',
            },
        ),
        migrations.CreateModel(
            name='SHRMBDoctorsModel',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SHRMB Doctor',
                'verbose_name_plural': 'SHRMB Doctors',
            },
        ),
        migrations.CreateModel(
            name='SHRMBHistoryModel',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
            options={
                'verbose_name': 'SHRMB History',
                'verbose_name_plural': 'SHRMB Histories',
            },
        ),
        migrations.CreateModel(
            name='SHRMBVacanciesModel',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
            options={
                'verbose_name': 'SHRMB Vacancy',
                'verbose_name_plural': 'SHRMB Vacancies',
            },
        ),
    ]
