# Generated by Django 5.0.3 on 2024-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrmb_app', '0002_alter_shrmbadmissionmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrmbadmissionmodel',
            name='id',
            field=models.TextField(default='4d5c79dd78ae4108be9883cf1bfb515b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdepartmentmodel',
            name='id',
            field=models.TextField(default='4d5c79dd78ae4108be9883cf1bfb515b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdoctorsmodel',
            name='id',
            field=models.TextField(default='4d5c79dd78ae4108be9883cf1bfb515b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbhistorymodel',
            name='id',
            field=models.TextField(default='4d5c79dd78ae4108be9883cf1bfb515b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbvacanciesmodel',
            name='id',
            field=models.TextField(default='4d5c79dd78ae4108be9883cf1bfb515b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
