# Generated by Django 5.0.3 on 2024-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrmb_app', '0004_alter_shrmbadmissionmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrmbadmissionmodel',
            name='id',
            field=models.TextField(default='29a863e5d01e42d0a56b3bfb762bfdda', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdepartmentmodel',
            name='id',
            field=models.TextField(default='29a863e5d01e42d0a56b3bfb762bfdda', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdoctorsmodel',
            name='id',
            field=models.TextField(default='29a863e5d01e42d0a56b3bfb762bfdda', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbhistorymodel',
            name='id',
            field=models.TextField(default='29a863e5d01e42d0a56b3bfb762bfdda', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbhistorymodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='3055b8411e9b420ca3f1ee0be92f6faa.jpg'),
        ),
        migrations.AlterField(
            model_name='shrmbvacanciesmodel',
            name='id',
            field=models.TextField(default='29a863e5d01e42d0a56b3bfb762bfdda', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
