# Generated by Django 5.0.3 on 2024-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrmb_app', '0005_alter_shrmbadmissionmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrmbadmissionmodel',
            name='id',
            field=models.TextField(default='a149d7083e9544f38c02f4eba3d016fa', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdepartmentmodel',
            name='id',
            field=models.TextField(default='a149d7083e9544f38c02f4eba3d016fa', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdoctorsmodel',
            name='id',
            field=models.TextField(default='a149d7083e9544f38c02f4eba3d016fa', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbhistorymodel',
            name='id',
            field=models.TextField(default='a149d7083e9544f38c02f4eba3d016fa', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbhistorymodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='8d672f9e3b6c46ed90953415eff9e968.jpg'),
        ),
        migrations.AlterField(
            model_name='shrmbvacanciesmodel',
            name='id',
            field=models.TextField(default='a149d7083e9544f38c02f4eba3d016fa', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
