# Generated by Django 5.0.3 on 2024-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrmb_app', '0006_alter_shrmbadmissionmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrmbadmissionmodel',
            name='id',
            field=models.TextField(default='34cb31e52b274a8096c9dec7d0c1e93d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdepartmentmodel',
            name='id',
            field=models.TextField(default='34cb31e52b274a8096c9dec7d0c1e93d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbdoctorsmodel',
            name='id',
            field=models.TextField(default='34cb31e52b274a8096c9dec7d0c1e93d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbhistorymodel',
            name='id',
            field=models.TextField(default='34cb31e52b274a8096c9dec7d0c1e93d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shrmbhistorymodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='shrmbvacanciesmodel',
            name='id',
            field=models.TextField(default='34cb31e52b274a8096c9dec7d0c1e93d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
